# Generated by Django 3.2 on 2021-04-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100, null=True)),
                ('type_document', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF'), ('RG', 'RG')], max_length=50)),
                ('document', models.CharField(max_length=50, unique=True)),
                ('job', models.CharField(choices=[('PO', 'Programador'), ('BD', 'DBA'), ('GP', 'Gerente')], max_length=50)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('comercial', 'Comercial'), ('residencial', 'Residencial')], max_length=12)),
                ('number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
    ]
