# Generated by Django 3.2 on 2021-04-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='selecao.candidate'),
            preserve_default=False,
        ),
    ]
